### ISSUE TITLE
Some optimization suggestions for the experience.

### ISSUE THREAD

**Issue by wizardAEI** [ntegrals/aura-voice#11]
Hello，I'm glad to see your email!
The concept of the website is great, and achieving low-latency Q&A results is also impressive.

**Is your feature request related to a problem? Please describe.**
Can the website add button click sound effects for reminders, as well as animations after the button is pressed? This would enhance the interactive experience. Additionally, can it display the user's speech recognition text in real-time (streaming display)? This way, users will have more certainty about their questions.

**Describe the solution you'd like**
For example, add an animation that shrinks the voice ball when the button is pressed, using a Bézier curve to make the action smoother; 
To display user questions in a streaming manner, you may need to use services from other cloud providers to achieve this. such as https://learn.microsoft.com/azure/ai-services/speech-service/get-started-speech-to-text?tabs=macos%2Cterminal&pivots=ai-studio

**Comment by ntegrals** [comment]
Thanks for the great suggestion 🙏 I think animating the ball when pressed is a great idea. I'll research how to best implement something like this.
