### ISSUE TITLE
Discussion on how improve usability

### ISSUE THREAD

**Issue by pedrohwbauer** [ntegrals/aura-voice#7]
I found the "Listening" and "Thinking" notifications to be a little confusing at first.
When I click the button at the bottom, I'm not paying attention on what happens at the top of the page. Maybe putting the notifications closer to the button would help.
But what I think would really improve usablility would be some animation, like putting a microfone icon when user is speaking or having waves vibrating to the user's voice, and then having some loading animation when the assistant is thinking.

**Comment by ntegrals** [comment]
Fantastic ideas, I'll research the best implementation 🙌
