### ISSUE TITLE
Improve AssistantButton code?

### ISSUE THREAD

**Issue by brodycj** [ntegrals/aura-voice#8]
Hey @ntegrals!

I took a quick look through the code ... wonder if you could refactor some of the code in AssistantButton.tsx, move some into helper functions or even look into what could be provided from npm packages?

Or maybe, somehow, see if you can break any components out of AssistantButton, such as the toast notifications?

In general, I would personally be more biased towards separating the logic code from presentation as much as possible, here is a really nice counterpoint against my own bias: https://matt-rickard.com/presentation-next-to-code

**Comment by ntegrals** [comment]
Thanks for the wonderful suggestions 🙏 I'll dive into refactoring soon. (I'm thinking about a major rewrite to improve functionality, so might do this afterwards.)
